#!/bin/sh
. "$(dirname "$0")/scripts/husky.sh"

echo 'test'
sh "$(dirname "$0")/scripts/remove-console.sh"
sh "$(dirname "$0")/scripts/check-todo.sh"
# 开启子shell处理 防止中断提交
npm run lint-new &

wait 
# # commit_msg=
# echo "$1"

# echo "$?"

